// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin_Projekt.Models;

namespace Pin_Projekt.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190830112224_Obrada_Podataka")]
    partial class Obrada_Podataka
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pin_Projekt.Models.Obrada_Podataka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Etiketa");

                    b.Property<string>("Ime_Proizvoda");

                    b.Property<string>("Izgled_Proizvoda");

                    b.Property<string>("Tržište");

                    b.Property<int>("Čep");

                    b.HasKey("ID");

                    b.ToTable("Obrada_Podataka");
                });
#pragma warning restore 612, 618
        }
    }
}
